platform :ios, '8.0'

target 'BWObjective-CResearch-iOS' do

  pod 'Masonry'
  pod 'FMDB', '~> 2.7.2'
  pod 'AFNetworking', '~> 3.1.0'
  pod 'YYCategories', '~> 1.0.4'
  pod 'BWPodRepository', '0.2.0'

  target 'BWObjective-CResearch-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BWObjective-CResearch-iOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
